### PR TITLE
Filter out archived Toggl projects from menu

### PR DESCRIPTION
**Pull request by sortofworks**
This PR also filters out projects that have been archived.

https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md

### CODE REVIEW

**Comment by godbout** [comment]
thanks!

i'll have a look in the following days on how Toggl handles archived projects (like can you still start a timer with an archived project, etc). depending on the situation, i might merge, or discuss. will need tests too.

**Comment by godbout** [comment]
checked. good catch. will merge, refactor and add tests. thanks!

**Comment by godbout** [comment]
can you check if it's working the way you are expecting? https://github.com/godbout/alfred-time/releases/tag/4.2.0

thanks!

**Comment by sortofworks** [comment]
The filter works great. Thanks for the help!
Time.alfredworkflow still says 4.1.0 btw.

**Comment by godbout** [comment]
oops 😬️

the release process of the Workflow itself is a pain. i've updated the file, can you try again? please note that i might have fucked it up again, who knows.

**Comment by sortofworks** [comment]
It says 4.2.0 now, spelling is updated at as well. 
Cheers :)

**Comment by godbout** [comment]
fantastic. enjoy! thanks for the PR.

**Pull request merged**
